name: Check Syntax

on:
  push:
    branches:
      - main

jobs:
  check_syntax:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.9, 3.11]

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install flake8 and unittest
        run: |
          python -m pip install flake8 unittest

      - name: Display Python version
        run: python --version

      - name: Run flake8
        run: |
          flake8

      - name: Run unittest
        run: |
          python -m unittest discover -s tests -p "*_test.py"
