name: Check Python Version

on:
  push:
    branches:
      - check_python_version

jobs:
  check_python:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Display Python version
        run: python --version
